name: "\u23f0 Daily Contribution"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  make-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "Last update: $(date)" > .github/daily-update.txt

      - name: Commit changes
        uses: ./.github/actions/commit-and-push
        with:
          files: .github/daily-update.txt
          commit-message: "chore: ‚è∞ daily contribution"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
